export const GET_POKEMONS_REQUEST = 'GET_POKEMONS_REQUEST'
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS'
export const GET_POKEMONS_FAIL = 'GET_POKEMONS_FAIL'
export const SET_POKEMONS = 'SET_POKEMONS'
export const FILTER_POKEMONS = 'FILTER_POKEMONS'

export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST'
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS'
export const GET_POKEMON_FAIL = 'GET_POKEMON_FAIL'
export const SET_POKEMON = 'SET_POKEMON'

export const GET_POKEMON_SPECIES_REQUEST = 'GET_POKEMON_SPECIES_REQUEST'
export const GET_POKEMON_SPECIES_SUCCESS = 'GET_POKEMON_SPECIES_SUCCESS'
export const GET_POKEMON_SPECIES_FAIL = 'GET_POKEMON_SPECIES_FAIL'
export const SET_POKEMON_SPECIES = 'SET_POKEMON_SPECIES'

export const GET_POKEMON_EVOLUTION_CHAIN_REQUEST =
  'GET_POKEMON_EVOLUTION_CHAIN_REQUEST'
export const GET_POKEMON_EVOLUTION_CHAIN_SUCCESS =
  'GET_POKEMON_EVOLUTION_CHAIN_SUCCESS'
export const GET_POKEMON_EVOLUTION_CHAIN_FAIL =
  'GET_POKEMON_EVOLUTION_CHAIN_FAIL'
export const SET_POKEMON_EVOLUTION_CHAIN = 'SET_POKEMON_EVOLUTION_CHAIN'

export const ADD_POKEMON_TO_FAVOURITES = 'ADD_POKEMON_TO_FAVOURITES'
export const REMOVE_POKEMON_FROM_FAVOURITES = 'REMOVE_POKEMON_FROM_FAVOURITES'
